import './global.css';
import { NextAuthProvider } from './providers';
export const metadata = {
  title: 'Rectrute.in',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <head>
        <link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'/>
        <link href='https://fonts.googleapis.com/css?family=Inter' rel='stylesheet' />
      </head>
      <body>
      <NextAuthProvider>
      {children}
      </NextAuthProvider>
      </body>
    </html>
  )
}
