import './global.css';
import { NextAuthProvider } from './providers';
import { ReduxProvider } from '@/lib/provider';

export const metadata = {
  title: 'Rectrute.in',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <NextAuthProvider>
      <ReduxProvider>
      {children}
      </ReduxProvider>
      </NextAuthProvider>
      </body>
    </html>
  )
}
